#!/usr/bin/env python3

import ctypes
import sys


def main() -> int:
    if len(sys.argv) != 2:
        return 2

    try:
        window_id = int(sys.argv[1], 0)
        x11 = ctypes.CDLL("libX11.so.6")
    except (OSError, ValueError):
        return 1

    x11.XOpenDisplay.argtypes = [ctypes.c_char_p]
    x11.XOpenDisplay.restype = ctypes.c_void_p
    x11.XMapRaised.argtypes = [ctypes.c_void_p, ctypes.c_ulong]
    x11.XSetInputFocus.argtypes = [
        ctypes.c_void_p,
        ctypes.c_ulong,
        ctypes.c_int,
        ctypes.c_ulong,
    ]
    x11.XFlush.argtypes = [ctypes.c_void_p]
    x11.XCloseDisplay.argtypes = [ctypes.c_void_p]

    display = x11.XOpenDisplay(None)
    if not display:
        return 1

    x11.XMapRaised(display, window_id)
    x11.XSetInputFocus(display, window_id, 1, 0)
    x11.XFlush(display)
    x11.XCloseDisplay(display)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())